[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = {}  # Scan the project directory with the default parameters

[project]
name = "te-cua"
version = "0.1"
description = "CUA Injection Tool"
authors = [
    {name = "Will Koester", email = "wikoeste@cisco.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "re",
    "json",
    "getpass",
    "setuptools",
    'cuautils'
]

[project.scripts]
cua = main.py